export default {
  route: {
    regStatus: 'Reg. state',
    Save: 'Save',
    Links: 'Links',
    Invoices: 'Invoices',
    Rents: 'Rents',
    Blocks: 'Blocks',
    dashboard: 'Dashboard',
    introduction: 'Introduction',
    documentation: 'Documentation',
    guide: 'Guide',
    permission: 'Permission',
    pagePermission: 'Page Permission',
    directivePermission: 'Directive Permission',
    icons: 'Icons',
    components: 'Components',
    componentIndex: 'Introduction',
    tinymce: 'Tinymce',
    markdown: 'Markdown',
    jsonEditor: 'JSON Editor',
    dndList: 'Dnd List',
    splitPane: 'SplitPane',
    avatarUpload: 'Avatar Upload',
    dropzone: 'Dropzone',
    sticky: 'Sticky',
    countTo: 'CountTo',
    componentMixin: 'Mixin',
    backToTop: 'BackToTop',
    dragDialog: 'Drag Dialog',
    dragSelect: 'Drag Select',
    dragKanban: 'Drag Kanban',
    charts: 'Charts',
    keyboardChart: 'Keyboard Chart',
    lineChart: 'Line Chart',
    mixChart: 'Mix Chart',
    example: 'Example',
    nested: 'Nested Routes',
    menu1: 'Menu 1',
    'menu1-1': 'Menu 1-1',
    'menu1-2': 'Menu 1-2',
    'menu1-2-1': 'Menu 1-2-1',
    'menu1-2-2': 'Menu 1-2-2',
    'menu1-3': 'Menu 1-3',
    menu2: 'Menu 2',
    tab: 'Tab',
    form: 'Form',
    createArticle: 'Create Article',
    editArticle: 'Edit Article',
    articleList: 'Article List',
    errorPages: 'Error Pages',
    page401: '401',
    page404: '404',
    errorLog: 'Error Log',
    excel: 'Excel',
    exportExcel: 'Export Excel',
    selectExcel: 'Export Selected',
    uploadExcel: 'Upload Excel',
    zip: 'Zip',
    pdf: 'PDF',
    exportZip: 'Export Zip',
    theme: 'Theme',
    clipboardDemo: 'Clipboard',
    i18n: 'I18n',
    caruselclub: 'Carusel.club',
    Objects: 'Objects',
    ObjectsList: 'Objects List',
    Dispatcher: 'Dispatcher',
    settingsTitle: 'Settings',
    Users: 'Users',
    Roles: 'Roles',
    TranslatesManagement: 'Translates Management',
    Logs: 'Logs',
    tariffsTitle: 'Tariffs',
    Tariffs: 'Tariffs',
    RentStates: 'Rent States',
    tariffOptions: 'Tariff Options',
    Bonuses: 'Bonuses',
    Promotion: 'Promotion',
    clientsTitle: 'Clients',
    clientsList: 'Clients List',
    rentsList: 'Rents',
    invoicesList: 'Invoices',
    editClients: 'Edit clients',
    rentForm: 'Rent',
    tariffForm: 'Tariff'
  },
  navbar: {
    logOut: 'Out',
    dashboard: 'Dashboard',
    help: 'Help',
    settings: 'Settings',
    support: 'Support'
  },
  login: {
    title: 'Carusel',
    logIn: 'Log in',
    username: 'Username',
    password: 'Password',
    any: 'any',
    thirdparty: 'Or connect with',
    thirdpartyTips: 'Can not be simulated on local, so please combine you own business simulation! ! !'
  },
  documentation: {
    documentation: 'Documentation',
    github: 'Github Repository'
  },
  permission: {
    roles: 'Your roles',
    switchRoles: 'Switch roles',
    tips: 'In some cases it is not suitable to use v-permission, such as element Tab component or el-table-column and other asynchronous rendering dom cases which can only be achieved by manually setting the v-if.'
  },
  guide: {
    description: 'The guide page is useful for some people who entered the project for the first time. You can briefly introduce the features of the project. Demo is based on ',
    button: 'Show Guide'
  },
  components: {
    documentation: 'Documentation',
    tinymceTips: 'Rich text editor is a core part of management system, but at the same time is a place with lots of problems. In the process of selecting rich texts, I also walked a lot of detours. The common rich text editors in the market are basically used, and the finally chose Tinymce. See documentation for more detailed rich text editor comparisons and introductions.',
    dropzoneTips: 'Because my business has special needs, and has to upload images to qiniu, so instead of a third party, I chose encapsulate it by myself. It is very simple, you can see the detail code in @/components/Dropzone.',
    stickyTips: 'when the page is scrolled to the preset position will be sticky on the top.',
    backToTopTips1: 'When the page is scrolled to the specified position, the Back to Top button appears in the lower right corner',
    backToTopTips2: 'You can customize the style of the button, show / hide, height of appearance, height of the return. If you need a text prompt, you can use element-ui el-tooltip elements externally',
    imageUploadTips: 'Since I was using only the vue@1 version, and it is not compatible with mockjs at the moment, I modified it myself, and if you are going to use it, it is better to use official version.'
  },
  table: {
    dynamicTips1: 'Fixed header, sorted by header order',
    dynamicTips2: 'Not fixed header, sorted by click order',
    dragTips1: 'The default order',
    dragTips2: 'The after dragging order',
    title: 'Title',
    importance: 'Imp',
    type: 'Type',
    remark: 'Remark',
    search: 'Search',
    add: 'Add',
    export: 'Export',
    reviewer: 'reviewer',
    id: 'ID',
    date: 'Date',
    author: 'Author',
    readings: 'Readings',
    status: 'Status',
    actions: 'Actions',
    edit: 'Edit',
    publish: 'Publish',
    draft: 'Draft',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm'
  },
  errorLog: {
    tips: 'Please click the bug icon in the upper right corner',
    description: 'Now the management system are basically the form of the spa, it enhances the user experience, but it also increases the possibility of page problems, a small negligence may lead to the entire page deadlock. Fortunately Vue provides a way to catch handling exceptions, where you can handle errors or report exceptions.',
    documentation: 'Document introduction'
  },
  excel: {
    export: 'Export',
    selectedExport: 'Export Selected Items',
    placeholder: 'Please enter the file name(default excel-list)'
  },
  zip: {
    export: 'Export',
    placeholder: 'Please enter the file name(default file)'
  },
  pdf: {
    tips: 'Here we use window.print() to implement the feature of downloading pdf.'
  },
  theme: {
    change: 'Change Theme',
    documentation: 'Theme documentation',
    tips: 'Tips: It is different from the theme-pick on the navbar is two different skinning methods, each with different application scenarios. Refer to the documentation for details.'
  },
  tagsView: {
    refresh: 'Refresh',
    close: 'Close',
    closeOthers: 'Close Others',
    closeAll: 'Close All'
  },
  cardpanel: {
    user: 'New user',
    rent: 'Total rent',
    transaction: 'Transaction',
    income: 'Income'
  },
  pieChart: {
    Trip: 'Trip',
    Park: 'Parking',
    Reserve: 'Reserve',
    Evaluate: 'Evaluate',
    Service: 'Service'
  },
  clientsForm: {
    clientInfo: 'Client info',
    passportInfo: 'Passport Info',
    licenseInfo: 'License Info',
    surname: 'Surname',
    name: 'Name',
    fathername: 'Fathername',
    phone: 'Phone',
    email: 'Email',
    sex: 'Sex',
    Male: 'Male',
    Female: 'Female',
    birthDate: 'Birth Date',
    smsCode: 'SMS Code',
    Codeword: 'Codeword',
    allowedDebt: 'Allowed Debt',
    Multiplier: 'Multiplier',
    refferalCode: 'Refferal Code',
    Tags: 'Tags',
    Description: 'Description',
    passportSeries: 'Passport Series',
    passportNumber: 'Passport Number',
    passportIssuedBy: 'Passport Issued By',
    passportRegistration: 'Passport Registration',
    passportDate: 'Passport Date',
    licenseSeries: 'License Series',
    licenseNumber: 'License Number',
    licenseValidDate: 'License Valid Date',
    drivingExperience: 'driving Experience',
    licenseDate: 'License Date',
    balance: 'Balance'
  },
  rentForm: {
    rentInfo: 'Rent Info',
    rentState: 'Rent State',
    rentHold: 'Rent Hold',
    rentId: 'Rent ID',
    phone: 'Phone number',
    clientName: 'Client Name',
    tariffName: 'Tariff Name',
    begin: 'Rent Begin',
    end: 'Rent End',
    regNumber: 'Reg.number',
    timestamp: 'Time',
    state: 'State',
    duration: 'Duration',
    mileage: 'Mileage',
    cost: 'Cost',
    costMileage: 'Cost Mileage'
  },
  tariffForm: {
    tariffSettings: 'Tariff Settings',
    holdSettings: 'Hold Settings',
    otherSettings: 'Other Settings',
    name: 'Name',
    calculationType: 'Calculation Type',
    minute: 'Minute',
    hourly: 'Hourly',
    daily: 'Daily',
    mileage: 'Mileage',
    reserveCancelCount: 'Reserve Cancel Count',
    freeTime: 'FreeTime',
    freeEvaluateTime: 'Free Evaluate Time',
    freeMileage: 'Free Mileage',
    costMileage: 'Cost Mileage',
    beginHoldState: 'Begin Hold State',
    minInvoiceCost: 'Min Invoice Cost',
    prepay: 'Prepay',
    holdCost: 'Hold Cost',
    holdInterval: 'Hold Interval',
    reserve: 'Reserve',
    evaluate: 'Evaluate',
    trip: 'Trip',
    park: 'Park'
  },
  objectForm: {
    name: 'Name',
    model: 'Model',
    imei: 'IMEI',
    regNumber: 'Reg. Number',
    time: 'Last Position Time',
    status: 'Status',
    rent: 'Rent State'
  },
  objects: {
    command: 'Command',
    send: 'Send'
  },
  rents: {
    available: 'Available',
    reserve: 'Reserve',
    evalute: 'Evalute',
    trip: 'Trip',
    park: 'Parking',
    service: 'Service',
    none: 'None'
  },
  commands: {
    info: 'Request Information',
    state: 'Request Current State',
    doorLock: 'Door Lock',
    doorUnlock: 'Door Unlock',
    guardOn: 'Guard On',
    guardOff: 'Guard Off',
    engineLock: 'Engine Lock',
    engineUnlock: 'Engine Unlock',
    engineOn: 'Engine On',
    engineOff: 'Engine Off',
    blink: 'Blink',
    horn: 'Horn'
  },
  mapTypes: {
    osm: 'Open Street',
    google: 'Google',
    googlesat: 'Google Satellite',
    yandex: 'Yandex'
  },
  error404: {
    ops: 'Ops!',
    message: 'Something went wrong...',
    info: 'Sorry! Page not found',
    home: 'To home'
  },
  common: {
    success: 'Success',
    success_cmd: 'Command "{cmd}" executed: {msg}',
    success_rent: 'Rent state changed to "{state}"',
    error: 'Error',
    error_cmd: 'Command "{cmd}" not executed: {msg}',
    error_rent: 'Rent state not changed to "{state}": {msg}',
    error_notimpl: 'not implemented'
  }
}
