// to do: module translate in separate classes
export default {
  route: {
    regStatus: 'Статус рег.',
    Save: 'Сохранить',
    Delete: 'Удалить',
    Create: 'Создать',
    Links: 'Ссылки',
    Invoices: 'Счета',
    Rents: 'Аренды',
    Blocks: 'Блокировки',
    dashboard: 'Рабочий стол',
    introduction: 'Введение',
    documentation: 'Документация',
    guide: 'Гайд',
    permission: 'Права доступа',
    pagePermission: 'Права доступа на страницу',
    directivePermission: 'Directive Permission',
    icons: 'Иконки',
    components: 'Компоненты',
    componentIndex: 'Введение',
    tinymce: 'Tinymce',
    markdown: 'Markdown',
    jsonEditor: 'JSON Editor',
    dndList: 'Dnd List',
    splitPane: 'SplitPane',
    avatarUpload: 'Avatar Upload',
    dropzone: 'Dropzone',
    sticky: 'Sticky',
    countTo: 'CountTo',
    componentMixin: 'Mixin',
    backToTop: 'BackToTop',
    dragDialog: 'Drag Dialog',
    dragSelect: 'Drag Select',
    dragKanban: 'Drag Kanban',
    charts: 'Charts',
    keyboardChart: 'Keyboard Chart',
    lineChart: 'Line Chart',
    mixChart: 'Mix Chart',
    example: 'Example',
    nested: 'Nested Routes',
    menu1: 'Menu 1',
    'menu1-1': 'Menu 1-1',
    'menu1-2': 'Menu 1-2',
    'menu1-2-1': 'Menu 1-2-1',
    'menu1-2-2': 'Menu 1-2-2',
    'menu1-3': 'Menu 1-3',
    menu2: 'Menu 2',
    tab: 'Tab',
    form: 'Form',
    createArticle: 'Create Article',
    editArticle: 'Edit Article',
    articleList: 'Article List',
    errorPages: 'Error Pages',
    page401: '401',
    page404: '404',
    errorLog: 'Error Log',
    excel: 'Excel',
    exportExcel: 'Export Excel',
    selectExcel: 'Export Selected',
    uploadExcel: 'Upload Excel',
    zip: 'Zip',
    pdf: 'PDF',
    exportZip: 'Export Zip',
    theme: 'Theme',
    clipboardDemo: 'Clipboard',
    i18n: 'I18n',
    caruselclub: 'Carusel.club',
    Objects: 'Объекты',
    ObjectsList: 'Список объектов',
    Dispatcher: 'Диспетчер',
    settingsTitle: 'Настройки',
    Users: 'Пользователи',
    Roles: 'Роли',
    TranslatesManagement: 'Менеджер переводов',
    Logs: 'Логи',
    tariffsTitle: 'Тарифы ',
    Tariffs: 'Тарифы',
    RentStates: 'Арендные состояния',
    tariffOptions: 'Тарифные опции',
    Bonuses: 'Бонусы',
    Promotion: 'Акции',
    clientsTitle: 'Клиенты',
    clientsList: 'Список клиентов',
    rentsList: 'Аренды',
    invoicesList: 'Счета',
    editClients: 'Редактирование клиента',
    rentForm: 'Аренда',
    tariffForm: 'Тариф'
  },
  navbar: {
    logOut: 'Выход',
    dashboard: 'Домой',
    help: 'Помощь',
    settings: 'Настройки',
    support: 'Поддержка'
  },
  nav: {
    Objects: 'сервис'
  },
  login: {
    title: 'Carusel',
    logIn: 'Log in',
    username: 'Username',
    password: 'Password',
    any: 'any',
    thirdparty: 'Or connect with',
    thirdpartyTips: 'Can not be simulated on local, so please combine you own business simulation! ! !'
  },
  documentation: {
    documentation: 'Documentation',
    github: 'Github Repository'
  },
  permission: {
    roles: 'Your roles',
    switchRoles: 'Switch roles',
    tips: 'In some cases it is not suitable to use v-permission, such as element Tab component or el-table-column and other asynchronous rendering dom cases which can only be achieved by manually setting the v-if.'
  },
  guide: {
    description: 'The guide page is useful for some people who entered the project for the first time. You can briefly introduce the features of the project. Demo is based on ',
    button: 'Show Guide'
  },
  components: {
    documentation: 'Documentation',
    tinymceTips: 'Rich text editor is a core part of management system, but at the same time is a place with lots of problems. In the process of selecting rich texts, I also walked a lot of detours. The common rich text editors in the market are basically used, and the finally chose Tinymce. See documentation for more detailed rich text editor comparisons and introductions.',
    dropzoneTips: 'Because my business has special needs, and has to upload images to qiniu, so instead of a third party, I chose encapsulate it by myself. It is very simple, you can see the detail code in @/components/Dropzone.',
    stickyTips: 'when the page is scrolled to the preset position will be sticky on the top.',
    backToTopTips1: 'When the page is scrolled to the specified position, the Back to Top button appears in the lower right corner',
    backToTopTips2: 'You can customize the style of the button, show / hide, height of appearance, height of the return. If you need a text prompt, you can use element-ui el-tooltip elements externally',
    imageUploadTips: 'Since I was using only the vue@1 version, and it is not compatible with mockjs at the moment, I modified it myself, and if you are going to use it, it is better to use official version.'
  },
  table: {
    dynamicTips1: 'Fixed header, sorted by header order',
    dynamicTips2: 'Not fixed header, sorted by click order',
    dragTips1: 'The default order',
    dragTips2: 'The after dragging order',
    title: 'Title',
    importance: 'Imp',
    type: 'Type',
    remark: 'Remark',
    search: 'Search',
    add: 'Add',
    export: 'Export',
    reviewer: 'reviewer',
    id: 'ID',
    date: 'Date',
    author: 'Author',
    readings: 'Readings',
    status: 'Status',
    actions: 'Actions',
    edit: 'Edit',
    publish: 'Publish',
    draft: 'Draft',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm'
  },
  errorLog: {
    tips: 'Please click the bug icon in the upper right corner',
    description: 'Now the management system are basically the form of the spa, it enhances the user experience, but it also increases the possibility of page problems, a small negligence may lead to the entire page deadlock. Fortunately Vue provides a way to catch handling exceptions, where you can handle errors or report exceptions.',
    documentation: 'Document introduction'
  },
  excel: {
    export: 'Export',
    selectedExport: 'Export Selected Items',
    placeholder: 'Please enter the file name(default excel-list)'
  },
  zip: {
    export: 'Export',
    placeholder: 'Please enter the file name(default file)'
  },
  pdf: {
    tips: 'Here we use window.print() to implement the feature of downloading pdf.'
  },
  theme: {
    change: 'Change Theme',
    documentation: 'Theme documentation',
    tips: 'Tips: It is different from the theme-pick on the navbar is two different skinning methods, each with different application scenarios. Refer to the documentation for details.'
  },
  tagsView: {
    refresh: 'Refresh',
    close: 'Close',
    closeOthers: 'Close Others',
    closeAll: 'Close All'
  },
  cardpanel: {
    user: 'Пользователи',
    rent: 'Аренды',
    transaction: 'Транзакций',
    income: 'Доход'
  },
  pieChart: {
    Trip: 'Поездка',
    Park: 'Парковка',
    Reserve: 'Бронь',
    Evaluate: 'Оценка',
    Service: 'Сервис'
  },
  clientsForm: {
    clientInfo: 'Информация о клиенте',
    passportInfo: 'Паспорт',
    licenseInfo: 'Водительское удостоверение',
    surname: 'Фамилия',
    name: 'Имя',
    fathername: 'Отчество',
    phone: 'Телефон',
    email: 'Почта',
    sex: 'Пол',
    Male: 'Мужской',
    Female: 'Женский',
    birthDate: 'Дата рождения',
    smsCode: 'Код SMS',
    Codeword: 'Кодовое слово',
    allowedDebt: 'Доп. долг',
    Multiplier: 'Коэффициент',
    refferalCode: 'Реф.код',
    Tags: 'Тэги',
    Description: 'Описание',
    passportSeries: 'Серия паспорта',
    passportNumber: 'Номер паспорта',
    passportIssuedBy: 'Паспорт выдан',
    passportRegistration: 'Адрес регистрации',
    passportDate: 'Дата выдачи',
    licenseSeries: 'Серия ВУ',
    licenseNumber: 'Номер ВУ',
    licenseValidDate: 'ВУ действительно до',
    drivingExperience: 'Стаж',
    licenseDate: 'Дата выдачи ВУ',
    balance: 'Баланс'
  },
  rentForm: {
    rentInfo: 'Общая информация',
    rentState: 'Состояния аренды',
    rentHold: 'Холды аренды',
    rentId: 'ID аренды',
    phone: 'Телефон',
    clientName: 'ФИО',
    tariffName: 'Тариф',
    begin: 'Начало аренды',
    end: 'Конец аренды',
    regNumber: 'Гос.номер авто',
    timestamp: 'Время события',
    state: 'Состояние',
    duration: 'Продолжительность',
    mileage: 'Пробег',
    cost: 'Стоимость поездки'
  },
  tariffForm: {
    tariffSettings: 'Настройки',
    holdSettings: 'Холдирование',
    otherSettings: 'Дополнительно',
    name: 'Наименование',
    calculationType: 'Тарификация',
    minute: 'Минутный',
    hourly: 'Часовой',
    daily: 'Суточный',
    mileage: 'Пробег',
    reserveCancelCount: 'Количество отмен',
    freeTime: 'Время бронирования',
    freeEvaluateTime: 'Время оценки',
    freeMileage: 'Включенный пробег',
    costMileage: 'Плата за перепробег',
    beginHoldState: 'Состояния начала холда',
    minInvoiceCost: 'Минимальная сумма счета',
    prepay: 'Депозит',
    holdCost: 'Размер холда',
    holdInterval: 'Интервал холдирования',
    reserve: 'Бронирование',
    evaluate: 'Оценка',
    trip: 'Поездка',
    park: 'Парковка'
  },
  objectForm: {
    name: 'Наименование',
    model: 'Модель',
    imei: 'IMEI',
    regNumber: 'Рег.номер',
    time: 'Время посл.позиции',
    status: 'Состояние',
    rent: 'Аренда'
  },
  objects: {
    command: 'Команда',
    send: 'Отправить'
  },
  rents: {
    available: 'Свободна',
    reserve: 'Зарезервирована',
    evalute: 'Оценка',
    trip: 'Поездка',
    park: 'Парковка',
    service: 'Сервис',
    none: 'Нет'
  },
  commands: {
    info: 'Запрос информации',
    state: 'Запрос текущего состояния',
    doorLock: 'Открыть двери',
    doorUnlock: 'Закрыть двери',
    guardOn: 'Поставить под охрану',
    guardOff: 'Снять с охраны',
    engineLock: 'Заблокировать двигатель',
    engineUnlock: 'Разблокировать двигатель',
    engineOn: 'Завести двигатель',
    engineOff: 'Заглушить двигатель',
    blink: 'Поморгать фарами',
    horn: 'Посигналисть'
  },
  mapTypes: {
    osm: 'Open Street',
    google: 'Google',
    googlesat: 'Google Спутник',
    yandex: 'Yandex'
  },
  error404: {
    ops: 'Упс!',
    message: 'Что-то пошло не так...',
    info: 'Извините! Страница, которую Вы ищете, не может быть найдена',
    home: 'На главную'
  },
  common: {
    success: 'Выполнено',
    success_cmd: 'Команда "{cmd}" выполнена: {msg}',
    success_rent: 'Статус аренды изменён на "{state}"',
    error: 'Ошибка',
    error_cmd: 'Команда "{cmd}" не выполнена: {msg}',
    error_rent: 'Статус аренды не изменён на "{state}": {msg}',
    error_notimpl: 'не реализовано'
  }
}
